### ISSUE TITLE
Segfault with large messages

### ISSUE THREAD

**Issue by yrp604** [crossbeam-rs/crossbeam#112]
Hello,

So, up front this is my first rust project and it's very likely I'm screwing something up. I'm getting segfaults from inside msqueue when I have a large message. Messages sized 0x1000 don't kill it, 0x10000 do.

Code, adapted from a larger project:
```rust
extern crate crossbeam;

use std::sync::Arc;
use std::thread;
use crossbeam::sync::MsQueue;

struct B {
    data : [u8; 0x10000]
}

fn new_b() -> B {
    B { data :  [0; 0x10000] }
}

impl B {
    pub fn rx(
        &mut self,
        rx : Arc<MsQueue<B>>)
    {
        loop {
            let _ = rx.pop();
        }
    }
}


fn main() {
    let b_queue : Arc<MsQueue<B>> = Arc::new(MsQueue::new());

    {
        let mut c = new_b();
        let b_queue = b_queue.clone();

        thread::spawn(move || {
            c.rx(b_queue);
        });
    }

    loop {

    }
}
```

```
$ rust-gdb -q ../target/debug/msq-crash
Reading symbols from ../target/debug/msq-crash...done.
(gdb) r
Starting program: /home/joe/rust/msqueue-crash/target/debug/msq-crash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6fff700 (LWP 38768)]

Thread 2 "msq-crash" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6fff700 (LWP 38768)]
0x000055555556007f in crossbeam::sync::ms_queue::MsQueue<msq_crash::B>::pop<msq_crash::B> (self=<error reading variable: Cannot access memory at address 0x7ffff6dce4e0>)
    at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.2.10/src/sync/ms_queue.rs:241
241	    pub fn pop(&self) -> T {
(gdb) bt
#0  0x000055555556007f in crossbeam::sync::ms_queue::MsQueue<msq_crash::B>::pop<msq_crash::B> (self=<error reading variable: Cannot access memory at address 0x7ffff6dce4e0>)
    at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.2.10/src/sync/ms_queue.rs:241
#1  0x00005555555635d0 in msq_crash::B::rx (self=0x7ffff6e9e8e8, rx=Arc<crossbeam::sync::ms_queue::MsQueue<msq_crash::B>> = {...}) at /home/joe/rust/msqueue-crash/src/main.rs:21
#2  0x0000555555563d28 in msq_crash::main::{{closure}} () at /home/joe/rust/msqueue-crash/src/main.rs:35
#3  0x000055555556311b in std::panic::{{impl}}::call_once<(),closure> (self=<error reading variable: value of type `std::panic::AssertUnwindSafe<closure>' requires 65544 bytes, which is more than max-value-size>,
    _args=()) at /build/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
#4  0x000055555555c6c9 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=0x7ffff6f5ebc8 "\000") at /build/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
#5  0x000055555557badb in panic_unwind::__rust_maybe_catch_panic () at /build/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
#6  0x000055555555c2fa in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> (
    f=<error reading variable: value of type `std::panic::AssertUnwindSafe<closure>' requires 65544 bytes, which is more than max-value-size>) at /build/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
#7  0x000055555555b5a5 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (
    f=<error reading variable: value of type `std::panic::AssertUnwindSafe<closure>' requires 65544 bytes, which is more than max-value-size>) at /build/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
#8  0x000055555556398d in std::thread::{{impl}}::spawn::{{closure}}<closure,()> () at /build/rustc-1.14.0+dfsg1/src/libstd/thread/mod.rs:287
#9  0x000055555555fbda in alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7ffff7044c40, args=()) at /build/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:595
#10 0x00005555555721b5 in alloc::boxed::{{impl}}::call_once<(),()> () at /build/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:605
#11 std::sys_common::thread::start_thread () at /build/rustc-1.14.0+dfsg1/src/libstd/sys_common/thread.rs:21
#12 std::sys::imp::thread::{{impl}}::new::thread_start () at /build/rustc-1.14.0+dfsg1/src/libstd/sys/unix/thread.rs:84
#13 0x00007ffff79c0464 in start_thread (arg=0x7ffff6fff700) at pthread_create.c:333
#14 0x00007ffff74ec9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

This crash does not occur when I build with '--release'. I'm guessing this is related to [this?](https://github.com/rust-lang/rust/issues/16012)

Am happy to provide any other info I can. Tested on both macOS 10.12 and debian running linux 4.8.

**Comment by ticki** [comment]
Are anyone able to reproduce this?

**Comment by BurntSushi** [comment]
Seems like this is probably a case of blowing the stack?
